[tool.poetry]
name = "node_graph_api"
version = "0.1.0"
description = ""
readme = "README.md"
authors = [
  "Synthbot Anon <synthbot.anon@gmail.com>"
]

[tool.poetry.dependencies]
python = "^3.11"
horsona = { git = "https://github.com/synthbot-anon/horsona", rev = "31e4a48cc8b4a9cedb0f199ee29acc2afc8efd6d" }


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

